### ISSUE TITLE
Doesn't tensorflow-directml-plugin only support TF 2.10.0?

### ISSUE THREAD

**Issue by ConnoisseurProtege** [muyeed15/DirectML-TensorFlow-PyTorch-Guide#1]
As title says, when I do pip install for `tensorflow-directml-plugin`, it forces the use of tensorflow 2.10.0. Is there a way to bypass this?

**Comment by muyeed15** [comment]
Hey, thanks for pointing that out! You actually helped me catch a mistake in the guide—I had tensorflow-cpu==2.17.0 in there, but it should've been 2.10.0. My bad on that one.

As for your issue, yeah, the tensorflow-directml-plugin is locked to tensorflow-cpu==2.10.0, and there's not much we can do about it right now. Microsoft hasn't pushed any updates to support newer TensorFlow versions, so we're kind of stuck with 2.10.0 until they do.

I know it’s not ideal, but if you need DirectML, you'll have to roll with tensorflow-cpu==2.10.0 for now. Hopefully, Microsoft gets around to updating it soon. Thanks again for the heads-up!
